---
# - name: "Add NGINX Signing Key"
#   apt_key:
#     url: http://nginx.org/keys/nginx_signing.key

# - name: "Add NGINX Repository"
#   apt_repository:
#     repo: "{{item}}"
#   with_items:
#     - deb http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
#     - deb-src http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx

- name: "Install NGINX"
  package:
    name: nginx
    state: latest
  notify: "Start NGINX"

- name: Create nginx config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
    #validate: 'nginx -t -c %s'
  notify: "Start NGINX"

- name: Create snippets directory
  file:
    path: "/etc/nginx/snippets"
    mode: 0755
    owner: "root"
    group: "root"
    state: directory
  notify: "Start NGINX"

- name: Create tls snippet
  template:
    src: tls.conf.j2
    dest: "/etc/nginx/snippets/tls.conf"
    owner: root
    group: root
    mode: 0644
    # validate: 'nginx -t -c %s'
  notify:
   - "Start NGINX"

- include_tasks: vhosts.yml

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes

