---

- name: apt-get update & aptitude full-upgrade
  apt:
    autoclean: yes
    update_cache: yes
    upgrade: "full"

- name: apt-get dist-upgrade
  apt:
    autoclean: yes
    update_cache: no
    upgrade: "dist"

#- name: Install ansible module dependencies
#  apt:
#    name: python-lxml
#    state: latest

- name: Make sure necessary scripts are installed
  apt:
    name: ['apt-transport-https', 'debian-goodies', 'lsof', 'molly-guard', 'python-pip']
    state: present

- name: Check if reboot needed
  stat: path=/var/run/reboot-required
  register: reboot_required

# reboot required, let us reboot ...
- block:
    - name: reboot
      command: reboot
#      command: /lib/molly-guard/reboot
      async: 0
      poll:  0

    - name: Waiting for server to reboot
      wait_for_connection:
        delay: 75

  when: reboot_required.stat.exists

# no reboot required, lets see if we need to restart services
- block:
    - name: List services needing a restart (1/2)
      shell: checkrestart | grep ^service | grep -v "nginx-debug" | cut -d' ' -f2
      register: services
      changed_when: False

    - name: List services needing a restart (2/2)
      debug:
        msg: >-
          Restarting {{ services.stdout_lines | count }} services:
          {{ services.stdout_lines | join(', ') }}

    - name: Restarting services
      service:
        name: "{{ item }}"
        state: restarted
      with_items: "{{ services.stdout_lines }}"

  when: not reboot_required.stat.exists
